// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiFtS54V1PBib9pHNUo4ouA5KtameJOiU',
    appId: '1:543125156826:web:f80ece84c42ba8286c06e3',
    messagingSenderId: '543125156826',
    projectId: 'regi-and-pw',
    authDomain: 'regi-and-pw.firebaseapp.com',
    storageBucket: 'regi-and-pw.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1em5jFxMW26SItp3-tJCKaLQzzNhxJ3I',
    appId: '1:543125156826:android:e464c55da29ea0676c06e3',
    messagingSenderId: '543125156826',
    projectId: 'regi-and-pw',
    storageBucket: 'regi-and-pw.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXqhljfGl6ysCXsqfwn6IjH_hU-t4X0zw',
    appId: '1:543125156826:ios:a7b24af1ab25026d6c06e3',
    messagingSenderId: '543125156826',
    projectId: 'regi-and-pw',
    storageBucket: 'regi-and-pw.firebasestorage.app',
    iosBundleId: 'com.example.registrationForgetpassword',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXqhljfGl6ysCXsqfwn6IjH_hU-t4X0zw',
    appId: '1:543125156826:ios:a7b24af1ab25026d6c06e3',
    messagingSenderId: '543125156826',
    projectId: 'regi-and-pw',
    storageBucket: 'regi-and-pw.firebasestorage.app',
    iosBundleId: 'com.example.registrationForgetpassword',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiFtS54V1PBib9pHNUo4ouA5KtameJOiU',
    appId: '1:543125156826:web:1b2f1f6598b5fa6b6c06e3',
    messagingSenderId: '543125156826',
    projectId: 'regi-and-pw',
    authDomain: 'regi-and-pw.firebaseapp.com',
    storageBucket: 'regi-and-pw.firebasestorage.app',
  );
}
